# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-23 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'High'), ('info', 'Normal'), ('success', 'Low')], default='denger', max_length=50),
            preserve_default=False,
        ),
    ]
